import { User, Project, Category, Task, Notification } from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-manager',
    name: 'Andi Triyanto (Manager)',
    email: 'manager@atdesign.com',
    role: 'MANAGER',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=160&q=80',
    specialization: 'Creative Director & Operations',
  },
  {
    id: 'user-havidh',
    name: 'Havidh',
    email: 'havidh@atdesign.com',
    role: 'DESIGNER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=160&q=80',
    specialization: 'Key Visual & Packaging',
  },
  {
    id: 'user-dara',
    name: 'Dara',
    email: 'dara@atdesign.com',
    role: 'DESIGNER',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=160&q=80',
    specialization: 'Marketplace Banner & Typography',
  },
  {
    id: 'user-azhar',
    name: 'Azhar',
    email: 'azhar@atdesign.com',
    role: 'DESIGNER',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=160&q=80',
    specialization: 'Vector & Promotional Graphic',
  },
  {
    id: 'user-content',
    name: 'Rian Creator',
    email: 'creator@atdesign.com',
    role: 'CONTENT_CREATOR',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=160&q=80',
    specialization: 'TikTok, Reels & Short Video',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-kurma',
    name: 'Kurma Campaign',
    code: 'PRJ-KURMA',
    status: 'ACTIVE',
    description: 'Ramadhan & Premium Dates series promotion assets and packaging.',
    color: '#D97706',
    createdAt: '2026-08-10T08:00:00Z',
  },
  {
    id: 'proj-shopee',
    name: 'Shopee Campaign',
    code: 'PRJ-SHOPEE',
    status: 'ACTIVE',
    description: 'Monthly 9.9, Payday & Flash Sale digital promotional banners.',
    color: '#EA580C',
    createdAt: '2026-08-15T08:00:00Z',
  },
  {
    id: 'proj-tiktok',
    name: 'TikTok Campaign',
    code: 'PRJ-TIKTOK',
    status: 'ACTIVE',
    description: 'Viral short videos, live stream cover templates and motion hooks.',
    color: '#0284C7',
    createdAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'proj-instagram',
    name: 'Instagram Campaign',
    code: 'PRJ-IG',
    status: 'ACTIVE',
    description: 'Organic carousel feeds, educational reels, and promotional stories.',
    color: '#E11D48',
    createdAt: '2026-08-25T08:00:00Z',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-poster', name: 'Poster', type: 'DESIGN' },
  { id: 'cat-banner', name: 'Marketplace Banner', type: 'DESIGN' },
  { id: 'cat-packaging', name: 'Packaging Design', type: 'DESIGN' },
  { id: 'cat-feed', name: 'Instagram Feed', type: 'DESIGN' },
  { id: 'cat-story', name: 'Story / Status', type: 'BOTH' },
  { id: 'cat-tiktok', name: 'TikTok', type: 'CONTENT' },
  { id: 'cat-reels', name: 'Reels', type: 'CONTENT' },
  { id: 'cat-video', name: 'Video', type: 'CONTENT' },
  { id: 'cat-marketplace', name: 'Marketplace Content', type: 'BOTH' },
  { id: 'cat-campaign', name: 'Campaign', type: 'BOTH' },
  { id: 'cat-product', name: 'Product Content', type: 'BOTH' },
];

// Helper to construct dynamic timestamps relative to now
const now = new Date();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    taskCode: 'AT-000124',
    title: 'Poster Shopee Kurma Akram 500g',
    projectId: 'proj-kurma',
    projectName: 'Kurma Campaign',
    categoryId: 'cat-poster',
    categoryName: 'Poster',
    taskType: 'Graphic Design',
    requester: 'Marketing Lead (Sarah)',
    assignedUserId: 'user-havidh',
    assignedUserName: 'Havidh',
    assignedUserAvatar: INITIAL_USERS[1].avatar,
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(24),
    startDate: hoursAgo(18),
    deadline: hoursFromNow(3.4), // 3h 24m remaining (Due Soon / On Track)
    estimatedWorkTime: '6 Jam',
    designBrief: 'Buat key visual poster Shopee untuk peluncuran Kurma Akram Premium 500g. Fokus pada nuansa eksklusif, halal, dan kesegaran produk.',
    objective: 'Meningkatkan CTR kunjungan toko di flash sale Shopee 9.9 dan brand awareness Kurma Akram.',
    targetAudience: 'Keluarga muslim modern, usia 25-45 tahun, pecinta produk makanan sehat & oleh-oleh haji.',
    designConcept: 'Minimalist, Elegant, Premium dengan warna dominan warm gold dan soft cream.',
    designClue: 'Gunakan visual premium dengan background cream. Produk harus menjadi focal point. Pertahankan kemasan original dan tambahkan badge Halal resmi.',
    reference: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=600&q=80',
    requiredText: 'KURMA AKRAM PREMIUM 500G - Manis Alami, Kualitas Terbaik. Promo Flash Sale Terbatas!',
    cta: 'Beli Sekarang di Shopee',
    platform: 'Shopee',
    dimension: '1080 x 1080 px',
    notes: 'File master PSD / AI wajib disimpan di shared drive setelah approved.',
    currentVersion: 'V1',
    revisionCount: 1,
    submissions: [
      {
        id: 'sub-1',
        taskId: 'task-1',
        version: 'V1',
        fileName: 'poster-kurma-akram-v1.jpg',
        fileType: 'image/jpeg',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        notes: 'Draft pertama dengan background cream lembut dan floating dates visual.',
        uploaderId: 'user-havidh',
        uploaderName: 'Havidh',
        uploadedAt: hoursAgo(8),
        status: 'REVISION_REQUESTED',
      },
    ],
    revisions: [
      {
        id: 'rev-1',
        taskId: 'task-1',
        revisionNumber: 1,
        requestedById: 'user-manager',
        requestedByName: 'Andi Triyanto (Manager)',
        requestedAt: hoursAgo(4),
        feedback: 'Produk terlalu kecil. Perbesar sekitar 15% dan kurangi elemen dekorasi di bagian sudut agar CTA lebih menonjol.',
        submissionVersion: 'V1',
      },
    ],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1',
        taskId: 'task-1',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created',
        details: 'Initial task creation with brief and design clues',
        timestamp: hoursAgo(24),
      },
      {
        id: 'log-2',
        taskId: 'task-1',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Assigned PIC',
        oldValue: 'Unassigned',
        newValue: 'Havidh',
        timestamp: hoursAgo(23.5),
      },
      {
        id: 'log-3',
        taskId: 'task-1',
        userId: 'user-havidh',
        userName: 'Havidh',
        userRole: 'DESIGNER',
        action: 'Status Changed',
        oldValue: 'ASSIGNED',
        newValue: 'IN_PROGRESS',
        details: 'Work started on key visual draft',
        timestamp: hoursAgo(18),
      },
      {
        id: 'log-4',
        taskId: 'task-1',
        userId: 'user-havidh',
        userName: 'Havidh',
        userRole: 'DESIGNER',
        action: 'Submitted V1',
        details: 'Uploaded poster-kurma-akram-v1.jpg',
        timestamp: hoursAgo(8),
      },
      {
        id: 'log-5',
        taskId: 'task-1',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Revision Requested',
        details: 'Produk terlalu kecil. Perbesar sekitar 15% dan kurangi elemen dekorasi.',
        timestamp: hoursAgo(4),
      },
    ],
    attachments: [
      {
        id: 'att-1',
        taskId: 'task-1',
        fileName: 'kurma_akram_pack_transparent.png',
        fileSize: '4.2 MB',
        fileType: 'image/png',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=400&q=80',
        uploadedBy: 'Andi Triyanto (Manager)',
        uploadedAt: hoursAgo(24),
      },
    ],
    comments: [
      {
        id: 'com-1',
        taskId: 'task-1',
        userId: 'user-havidh',
        userName: 'Havidh',
        userAvatar: INITIAL_USERS[1].avatar,
        content: 'Siap mas, sedang diperbesar 15% dan V2 akan di-submit siang ini.',
        createdAt: hoursAgo(3),
      },
    ],
  },
  {
    id: 'task-2',
    taskCode: 'AT-000125',
    title: 'Shopee Mega Sale 9.9 Main Header Banner',
    projectId: 'proj-shopee',
    projectName: 'Shopee Campaign',
    categoryId: 'cat-banner',
    categoryName: 'Marketplace Banner',
    taskType: 'Banner',
    requester: 'E-Commerce Manager',
    assignedUserId: 'user-dara',
    assignedUserName: 'Dara',
    assignedUserAvatar: INITIAL_USERS[2].avatar,
    priority: 'URGENT',
    status: 'UNDER_REVIEW',
    createdDate: hoursAgo(16),
    startDate: hoursAgo(12),
    deadline: hoursFromNow(1.5), // < 2 hours => Due Soon Warning
    estimatedWorkTime: '4 Jam',
    designBrief: 'Banner utama homepage toko Shopee ukuran desktop & mobile dengan promo Gratis Ongkir 0 Rupiah dan Diskon s.d 50%.',
    objective: 'High conversion banner for midnight sale countdown.',
    targetAudience: 'Shopee shoppers pencari diskon dan flash sale.',
    designConcept: 'Vibrant Deep Orange brand tone dengan typography bold dinamis.',
    designClue: 'Gunakan aksen Shopee Orange (#EE4D2D), typography tebal sans-serif, sertakan logo brand di pojok kiri atas.',
    requiredText: 'SHOPEE MEGA SALE 9.9 - DISKON HINGGA 50% + GRATIS ONGKIR RP0',
    cta: 'Klaim Voucher Sekarang',
    platform: 'Shopee',
    dimension: '1200 x 400 px',
    notes: 'Pastikan kontras teks sangat terbaca di mobile view.',
    currentVersion: 'V2',
    revisionCount: 1,
    submissions: [
      {
        id: 'sub-2a',
        taskId: 'task-2',
        version: 'V1',
        fileName: 'shopee-banner-v1.jpg',
        fileType: 'image/jpeg',
        fileUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        notes: 'Initial banner layout.',
        uploaderId: 'user-dara',
        uploaderName: 'Dara',
        uploadedAt: hoursAgo(6),
        status: 'REVISION_REQUESTED',
      },
      {
        id: 'sub-2b',
        taskId: 'task-2',
        version: 'V2',
        fileName: 'shopee-banner-v2-final.jpg',
        fileType: 'image/jpeg',
        fileUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        notes: 'Sudah diperbaiki: teks 50% dibuat lebih besar dan tombol voucher diberi highlight glow.',
        uploaderId: 'user-dara',
        uploaderName: 'Dara',
        uploadedAt: hoursAgo(1),
        status: 'PENDING_REVIEW',
      },
    ],
    revisions: [
      {
        id: 'rev-2',
        taskId: 'task-2',
        revisionNumber: 1,
        requestedById: 'user-manager',
        requestedByName: 'Andi Triyanto (Manager)',
        requestedAt: hoursAgo(3),
        feedback: 'Wording Diskon 50% kurang dominan, perjelas kontras di layar smartphone kecil.',
        submissionVersion: 'V1',
        resolvedAt: hoursAgo(1),
      },
    ],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-201',
        taskId: 'task-2',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created',
        timestamp: hoursAgo(16),
      },
      {
        id: 'log-202',
        taskId: 'task-2',
        userId: 'user-dara',
        userName: 'Dara',
        userRole: 'DESIGNER',
        action: 'Submitted V1',
        timestamp: hoursAgo(6),
      },
      {
        id: 'log-203',
        taskId: 'task-2',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Revision Requested',
        details: 'Wording Diskon 50% kurang dominan.',
        timestamp: hoursAgo(3),
      },
      {
        id: 'log-204',
        taskId: 'task-2',
        userId: 'user-dara',
        userName: 'Dara',
        userRole: 'DESIGNER',
        action: 'Submitted V2',
        details: 'Re-submitted revised banner V2',
        timestamp: hoursAgo(1),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-3',
    taskCode: 'AT-000126',
    title: 'TikTok Viral Hook Video: Unboxing Kurma Safawi',
    projectId: 'proj-tiktok',
    projectName: 'TikTok Campaign',
    categoryId: 'cat-tiktok',
    categoryName: 'TikTok',
    taskType: 'Video',
    requester: 'Social Media Lead',
    assignedUserId: 'user-content',
    assignedUserName: 'Rian Creator',
    assignedUserAvatar: INITIAL_USERS[4].avatar,
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(10),
    startDate: hoursAgo(8),
    deadline: hoursAgo(1.2), // Past deadline => OVERDUE
    estimatedWorkTime: '5 Jam',
    designBrief: 'Video pendek 15-25 detik teknik stop-motion / macro shot tekstur lembut kurma safawi.',
    objective: 'Mendapatkan minimal 50k views dan klik ke keranjang kuning.',
    targetAudience: 'Gen-Z & Millennial foodie.',
    designConcept: 'ASMR, satisfying unboxing dengan trending audio lofi arabian remix.',
    designClue: '0-3 detik pertama wajib langsung menampilkan daging kurma yang lumer saat dibelah dua.',
    requiredText: 'Kurma premium paling lembut yang pernah gue coba! 🔥',
    cta: 'Cek keranjang kuning sekarang',
    platform: 'TikTok',
    dimension: '1080 x 1920 px (9:16)',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-301',
        taskId: 'task-3',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created & Assigned to Rian Creator',
        timestamp: hoursAgo(10),
      },
    ],
    attachments: [],
    comments: [
      {
        id: 'com-301',
        taskId: 'task-3',
        userId: 'user-content',
        userName: 'Rian Creator',
        userAvatar: INITIAL_USERS[4].avatar,
        content: 'Sedang rendering transisi ASMR di Premiere, segera upload!',
        createdAt: hoursAgo(1.5),
      },
    ],
  },
  {
    id: 'task-4',
    taskCode: 'AT-000127',
    title: 'Instagram Carousel Edukasi: 5 Khasiat Rutin Kurma',
    projectId: 'proj-instagram',
    projectName: 'Instagram Campaign',
    categoryId: 'cat-feed',
    categoryName: 'Instagram Feed',
    taskType: 'Feed',
    requester: 'Content Strategist',
    assignedUserId: 'user-azhar',
    assignedUserName: 'Azhar',
    assignedUserAvatar: INITIAL_USERS[3].avatar,
    priority: 'MEDIUM',
    status: 'REVISION',
    createdDate: hoursAgo(30),
    startDate: hoursAgo(26),
    deadline: hoursFromNow(12),
    estimatedWorkTime: '5 Jam',
    designBrief: '5 Slide carousel edukasi kesehatan pencernaan, stamina, dan antioksidan.',
    objective: 'Save & share tinggi untuk feed organic growth.',
    targetAudience: 'Followers Instagram pegiat hidup sehat.',
    designConcept: 'Clean editorial layout dengan vector ilustrasi organ tubuh & buah kurma yang rapi.',
    designClue: 'Slide 1 buat headline rasa penasaran. Slide 2-4 poin inti. Slide 5 ringkasan + ajakan follow & save.',
    requiredText: 'Jangan Makan Kurma Sebelum Tau 5 Fakta Ini!',
    cta: 'Save postingan ini biar ga lupa!',
    platform: 'Instagram',
    dimension: '1080 x 1350 px (4:5)',
    currentVersion: 'V1',
    revisionCount: 2,
    submissions: [
      {
        id: 'sub-4',
        taskId: 'task-4',
        version: 'V1',
        fileName: 'carousel-kurma-5khasiat-v1.pdf',
        fileType: 'application/pdf',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        notes: 'Slide 1 sampai 5 sudah siap.',
        uploaderId: 'user-azhar',
        uploaderName: 'Azhar',
        uploadedAt: hoursAgo(12),
        status: 'REVISION_REQUESTED',
      },
    ],
    revisions: [
      {
        id: 'rev-4a',
        taskId: 'task-4',
        revisionNumber: 1,
        requestedById: 'user-manager',
        requestedByName: 'Andi Triyanto (Manager)',
        requestedAt: hoursAgo(9),
        feedback: 'Warna font di slide 3 agak pudar saat dibaca di dark mode smartphone.',
        submissionVersion: 'V1',
      },
      {
        id: 'rev-4b',
        taskId: 'task-4',
        revisionNumber: 2,
        requestedById: 'user-manager',
        requestedByName: 'Andi Triyanto (Manager)',
        requestedAt: hoursAgo(2),
        feedback: 'Kutipan referensi jurnal kedokteran tolong ditambahkan di slide terakhir sudut kanan bawah.',
        submissionVersion: 'V1',
      },
    ],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-401',
        taskId: 'task-4',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created',
        timestamp: hoursAgo(30),
      },
      {
        id: 'log-402',
        taskId: 'task-4',
        userId: 'user-azhar',
        userName: 'Azhar',
        userRole: 'DESIGNER',
        action: 'Submitted V1',
        timestamp: hoursAgo(12),
      },
      {
        id: 'log-403',
        taskId: 'task-4',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Revision Requested',
        details: 'Perbaiki kontras warna font slide 3 dan tambah referensi jurnal.',
        timestamp: hoursAgo(2),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-5',
    taskCode: 'AT-000128',
    title: 'Packaging Box Sleeve Edisi Spesial Kurma Ajwa 1kg',
    projectId: 'proj-kurma',
    projectName: 'Kurma Campaign',
    categoryId: 'cat-packaging',
    categoryName: 'Packaging Design',
    taskType: 'Packaging',
    requester: 'Head of Product Development',
    assignedUserId: 'user-dara',
    assignedUserName: 'Dara',
    assignedUserAvatar: INITIAL_USERS[2].avatar,
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(48),
    startDate: hoursAgo(40),
    deadline: hoursFromNow(8),
    estimatedWorkTime: '12 Jam',
    designBrief: 'Desain sleeve box hardbox untuk packaging Kurma Ajwa Madinah 1kg. Lengkap dengan foil emas hot stamping dan die cut pattern jendela intip produk.',
    objective: 'Kemasan eksklusif siap ekspor dan bingkisan parcel korporat.',
    targetAudience: 'Pasar gift premium, korporasi, hampers Idul Fitri.',
    designConcept: 'Luxury Islamic geometric pattern dipadu foil gold di atas base deep emerald black.',
    designClue: 'Garis die-cut harus presisi 3mm bleed margin. Sertakan barcode EAN-13 resmi di bagian belakang.',
    requiredText: 'KURMA AJWA AL-MADINAH AL-MUNAWWARAH - The Prophet Dates 1 KG',
    cta: 'Netto: 1000 Gram | BPOM RI & Halal Indonesia',
    platform: 'Print',
    dimension: '320 x 220 x 75 mm',
    currentVersion: 'V2',
    revisionCount: 1,
    submissions: [
      {
        id: 'sub-5a',
        taskId: 'task-5',
        version: 'V1',
        fileName: 'ajwa-sleeve-diecut-v1.pdf',
        fileType: 'application/pdf',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        notes: 'Submitted oleh Havidh sebelum dialihkan ke Dara.',
        uploaderId: 'user-havidh',
        uploaderName: 'Havidh',
        uploadedAt: hoursAgo(30),
        status: 'REVISION_REQUESTED',
      },
    ],
    revisions: [
      {
        id: 'rev-5',
        taskId: 'task-5',
        revisionNumber: 1,
        requestedById: 'user-manager',
        requestedByName: 'Andi Triyanto (Manager)',
        requestedAt: hoursAgo(24),
        feedback: 'Margin die cut terlalu dekat dengan lipatan samping 2mm, perlu digeser dan dialihkan ke Dara.',
        submissionVersion: 'V1',
      },
    ],
    reassignments: [
      {
        id: 'reassign-1',
        taskId: 'task-5',
        previousPicId: 'user-havidh',
        previousPicName: 'Havidh',
        newPicId: 'user-dara',
        newPicName: 'Dara',
        changedById: 'user-manager',
        changedByName: 'Andi Triyanto (Manager)',
        changedAt: hoursAgo(20),
        reason: 'Havidh fokus menyelesaikan Key Visual Campaign, dialihkan ke Dara spesialis kemasan die-cut.',
      },
    ],
    activityLogs: [
      {
        id: 'log-501',
        taskId: 'task-5',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created',
        timestamp: hoursAgo(48),
      },
      {
        id: 'log-502',
        taskId: 'task-5',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Assigned PIC',
        oldValue: 'Unassigned',
        newValue: 'Havidh',
        timestamp: hoursAgo(47),
      },
      {
        id: 'log-503',
        taskId: 'task-5',
        userId: 'user-havidh',
        userName: 'Havidh',
        userRole: 'DESIGNER',
        action: 'Submitted V1',
        timestamp: hoursAgo(30),
      },
      {
        id: 'log-504',
        taskId: 'task-5',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Changed PIC (Reassigned)',
        oldValue: 'Havidh',
        newValue: 'Dara',
        details: 'Reason: Havidh fokus menyelesaikan Key Visual, dialihkan ke Dara spesialis kemasan die-cut.',
        timestamp: hoursAgo(20),
      },
      {
        id: 'log-505',
        taskId: 'task-5',
        userId: 'user-dara',
        userName: 'Dara',
        userRole: 'DESIGNER',
        action: 'Status Changed',
        oldValue: 'REVISION',
        newValue: 'IN_PROGRESS',
        details: 'Dara melanjutkan penyesuaian bleed margin pada CAD packaging',
        timestamp: hoursAgo(18),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-6',
    taskCode: 'AT-000129',
    title: 'Shopee Flash Sale Hero Banner (Jam 12:00 - 15:00)',
    projectId: 'proj-shopee',
    projectName: 'Shopee Campaign',
    categoryId: 'cat-banner',
    categoryName: 'Marketplace Banner',
    taskType: 'Banner',
    requester: 'E-Commerce Marketing',
    assignedUserId: 'user-azhar',
    assignedUserName: 'Azhar',
    assignedUserAvatar: INITIAL_USERS[3].avatar,
    priority: 'HIGH',
    status: 'APPROVED',
    createdDate: hoursAgo(72),
    startDate: hoursAgo(60),
    deadline: hoursAgo(20),
    estimatedWorkTime: '3 Jam',
    designBrief: 'Banner Flash Sale Shopee harga coret Rp49.000.',
    objective: 'Flash sale instant checkout.',
    targetAudience: 'Shopee users.',
    designConcept: 'Urgent typography, lightning icon, countdown box placeholder.',
    designClue: 'Warna deep red orange dengan aksen kuning petir.',
    requiredText: 'FLASH SALE HANYA 3 JAM! DISKON KILAT 70%',
    cta: 'Serbu Sekarang!',
    platform: 'Shopee',
    dimension: '1080 x 1080 px',
    currentVersion: 'V2',
    revisionCount: 1,
    approvedBy: 'Andi Triyanto (Manager)',
    approvedAt: hoursAgo(22),
    completedAt: hoursAgo(22),
    submissions: [
      {
        id: 'sub-6',
        taskId: 'task-6',
        version: 'V2',
        fileName: 'shopee-flash-sale-v2.jpg',
        fileType: 'image/jpeg',
        fileUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        notes: 'Harga coret dan font flash sale sudah disesuaikan.',
        uploaderId: 'user-azhar',
        uploaderName: 'Azhar',
        uploadedAt: hoursAgo(24),
        status: 'APPROVED',
      },
    ],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-601',
        taskId: 'task-6',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Approved & Completed',
        oldValue: 'UNDER_REVIEW',
        newValue: 'APPROVED',
        details: 'Semua elemen sesuai brief dan disetujui untuk tayang.',
        timestamp: hoursAgo(22),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-7',
    taskCode: 'AT-000130',
    title: 'Instagram Story Poll: Kurma Sukari vs Kurma Medjool',
    projectId: 'proj-instagram',
    projectName: 'Instagram Campaign',
    categoryId: 'cat-story',
    categoryName: 'Story / Status',
    taskType: 'Story',
    requester: 'Community Lead',
    assignedUserId: 'user-content',
    assignedUserName: 'Rian Creator',
    assignedUserAvatar: INITIAL_USERS[4].avatar,
    priority: 'LOW',
    status: 'COMPLETED',
    createdDate: hoursAgo(90),
    startDate: hoursAgo(80),
    deadline: hoursAgo(40),
    estimatedWorkTime: '2 Jam',
    designBrief: 'Story interaktif voting favorit followers antara Sukari dan Medjool.',
    objective: 'Meningkatkan engagement rate dan interaksi sticker poll Instagram.',
    designConcept: 'Split screen vs visual dengan sticker area transparan.',
    requiredText: 'Kamu Tim Mana? Kurma Sukari Lembut atau Medjool Legit Jumbo?',
    cta: 'Vote di stiker bawah!',
    platform: 'Instagram',
    dimension: '1080 x 1920 px',
    currentVersion: 'V1',
    revisionCount: 0,
    approvedBy: 'Andi Triyanto (Manager)',
    approvedAt: hoursAgo(42),
    completedAt: hoursAgo(42),
    submissions: [
      {
        id: 'sub-7',
        taskId: 'task-7',
        version: 'V1',
        fileName: 'story-poll-sukari-medjool.jpg',
        fileType: 'image/jpeg',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        notes: 'Area tengah diberi space kosong untuk widget sticker poll IG.',
        uploaderId: 'user-content',
        uploaderName: 'Rian Creator',
        uploadedAt: hoursAgo(44),
        status: 'APPROVED',
      },
    ],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-701',
        taskId: 'task-7',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Approved & Completed',
        timestamp: hoursAgo(42),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-8',
    taskCode: 'AT-000131',
    title: 'TikTok Livestream Background Pin & Sticky Banner',
    projectId: 'proj-tiktok',
    projectName: 'TikTok Campaign',
    categoryId: 'cat-tiktok',
    categoryName: 'TikTok',
    taskType: 'Video',
    requester: 'Live Commerce Team',
    assignedUserId: 'user-content',
    assignedUserName: 'Rian Creator',
    assignedUserAvatar: INITIAL_USERS[4].avatar,
    priority: 'HIGH',
    status: 'ASSIGNED',
    createdDate: hoursAgo(5),
    deadline: hoursFromNow(5),
    estimatedWorkTime: '2 Jam',
    designBrief: 'Pin visual untuk live streaming host TikTok penunjuk voucher diskon koin.',
    objective: 'Mengarahkan penonton live stream agar segera checkout di etalase.',
    requiredText: 'VOUCHER LIVE 30% - KLIK ETALASE NO. 1 SEKARANG!',
    cta: 'Beli Saat Live',
    platform: 'TikTok',
    dimension: '1080 x 1920 px',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-801',
        taskId: 'task-8',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created & Assigned to Rian Creator',
        timestamp: hoursAgo(5),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-9',
    taskCode: 'AT-000132',
    title: 'Marketplace Product Catalog: Kurma Khalas 250g & 500g',
    projectId: 'proj-shopee',
    projectName: 'Shopee Campaign',
    categoryId: 'cat-marketplace',
    categoryName: 'Marketplace Content',
    taskType: 'Product Content',
    requester: 'Catalog Specialist',
    assignedUserId: 'user-havidh',
    assignedUserName: 'Havidh',
    assignedUserAvatar: INITIAL_USERS[1].avatar,
    priority: 'MEDIUM',
    status: 'SUBMITTED',
    createdDate: hoursAgo(20),
    startDate: hoursAgo(15),
    deadline: hoursFromNow(22),
    estimatedWorkTime: '4 Jam',
    designBrief: 'Set 5 foto produk utama dengan background putih bersih, detail tabel nutrisi, dan sertifikasi halal.',
    objective: 'Standar baku foto etalase marketplace Tokopedia & Shopee.',
    requiredText: 'Kurma Khalas Al-Saad - Manis Karamel Alami',
    dimension: '1000 x 1000 px',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [
      {
        id: 'sub-9',
        taskId: 'task-9',
        version: 'V1',
        fileName: 'khalas-catalog-set-5pcs.zip',
        fileType: 'application/zip',
        fileUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1546548970-71785318a17b?auto=format&fit=crop&w=800&q=80',
        notes: 'File zip berisi 5 variasi sudut foto katalog berformat JPG high res.',
        uploaderId: 'user-havidh',
        uploaderName: 'Havidh',
        uploadedAt: hoursAgo(2),
        status: 'PENDING_REVIEW',
      },
    ],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-901',
        taskId: 'task-9',
        userId: 'user-havidh',
        userName: 'Havidh',
        userRole: 'DESIGNER',
        action: 'Submitted V1 for Review',
        details: 'Uploaded 5 product catalog images',
        timestamp: hoursAgo(2),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-10',
    taskCode: 'AT-000133',
    title: 'Packaging Label Jar Kaca Kurma Choco Crunch',
    projectId: 'proj-kurma',
    projectName: 'Kurma Campaign',
    categoryId: 'cat-packaging',
    categoryName: 'Packaging Design',
    taskType: 'Packaging',
    requester: 'R&D Snack Division',
    assignedUserId: 'user-dara',
    assignedUserName: 'Dara',
    assignedUserAvatar: INITIAL_USERS[2].avatar,
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(14),
    startDate: hoursAgo(10),
    deadline: hoursFromNow(18),
    estimatedWorkTime: '6 Jam',
    designBrief: 'Sticker label keliling toples silinder kurma balut coklat renyah.',
    objective: 'Visual produk camilan anak muda modern.',
    designConcept: 'Playful yet premium, nuansa coklat leleh dan potongan almond.',
    dimension: '240 x 65 mm',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1001',
        taskId: 'task-10',
        userId: 'user-dara',
        userName: 'Dara',
        userRole: 'DESIGNER',
        action: 'Started Work',
        timestamp: hoursAgo(10),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-11',
    taskCode: 'AT-000134',
    title: 'Reels Video Recipe: Smoothie Kurma Pisang Oat',
    projectId: 'proj-instagram',
    projectName: 'Instagram Campaign',
    categoryId: 'cat-reels',
    categoryName: 'Reels',
    taskType: 'Video',
    requester: 'Nutritionist Partner',
    assignedUserId: 'user-content',
    assignedUserName: 'Rian Creator',
    assignedUserAvatar: INITIAL_USERS[4].avatar,
    priority: 'LOW',
    status: 'ASSIGNED',
    createdDate: hoursAgo(7),
    deadline: hoursFromNow(36),
    estimatedWorkTime: '4 Jam',
    designBrief: 'Video resep sarapan sehat penambah energi berbahan kurma sukari, pisang cavendish dan oat.',
    objective: 'Edukasi resep sehat sekaligus soft selling produk kurma.',
    dimension: '1080 x 1920 px (9:16)',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1101',
        taskId: 'task-11',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Created & Assigned',
        timestamp: hoursAgo(7),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-12',
    taskCode: 'AT-000135',
    title: 'Billboard & Digital Out-Of-Home (DOOH) Ramadhan Welcoming',
    projectId: 'proj-kurma',
    projectName: 'Kurma Campaign',
    categoryId: 'cat-campaign',
    categoryName: 'Campaign',
    taskType: 'Graphic Design',
    requester: 'Brand Director',
    assignedUserId: 'user-havidh',
    assignedUserName: 'Havidh',
    assignedUserAvatar: INITIAL_USERS[1].avatar,
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(36),
    startDate: hoursAgo(24),
    deadline: hoursAgo(0.5), // Past deadline by 30 mins => OVERDUE
    estimatedWorkTime: '8 Jam',
    designBrief: 'Desain LED DOOH Megatron Jalan Protokol Sudirman untuk Ramadhan Mubarak.',
    objective: 'High-impact mass brand presence.',
    dimension: '3840 x 1080 px (32:9 Ultra-wide)',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1201',
        taskId: 'task-12',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Task Assigned',
        timestamp: hoursAgo(36),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-13',
    taskCode: 'AT-000136',
    title: 'Shopee In-App Voucher Badge & Icon Assets',
    projectId: 'proj-shopee',
    projectName: 'Shopee Campaign',
    categoryId: 'cat-banner',
    categoryName: 'Marketplace Banner',
    taskType: 'Icon & Badge',
    requester: 'Growth Marketing',
    assignedUserId: 'user-azhar',
    assignedUserName: 'Azhar',
    assignedUserAvatar: INITIAL_USERS[3].avatar,
    priority: 'LOW',
    status: 'COMPLETED',
    createdDate: hoursAgo(120),
    startDate: hoursAgo(110),
    deadline: hoursAgo(70),
    estimatedWorkTime: '2 Jam',
    designBrief: 'Set 6 icon badge voucher diskon, gratis ongkir, cashback koin, dan COD.',
    objective: 'Icon seragam untuk penandaan produk diskon.',
    dimension: '512 x 512 px',
    currentVersion: 'V1',
    revisionCount: 0,
    approvedBy: 'Andi Triyanto (Manager)',
    approvedAt: hoursAgo(72),
    completedAt: hoursAgo(72),
    submissions: [
      {
        id: 'sub-13',
        taskId: 'task-13',
        version: 'V1',
        fileName: 'voucher-badges-pack.png',
        fileType: 'image/png',
        fileUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        previewUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=80',
        notes: '6 Badge vector PNG transparan resolusi tajam.',
        uploaderId: 'user-azhar',
        uploaderName: 'Azhar',
        uploadedAt: hoursAgo(75),
        status: 'APPROVED',
      },
    ],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1301',
        taskId: 'task-13',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Approved & Completed',
        timestamp: hoursAgo(72),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-14',
    taskCode: 'AT-000137',
    title: 'Story Q&A Template: Tanya Seputar Pilihan Kurma Terbaik',
    projectId: 'proj-instagram',
    projectName: 'Instagram Campaign',
    categoryId: 'cat-story',
    categoryName: 'Story / Status',
    taskType: 'Story',
    requester: 'Customer Care',
    assignedUserId: 'user-dara',
    assignedUserName: 'Dara',
    assignedUserAvatar: INITIAL_USERS[2].avatar,
    priority: 'LOW',
    status: 'DRAFT',
    createdDate: hoursAgo(2),
    deadline: hoursFromNow(48),
    estimatedWorkTime: '1.5 Jam',
    designBrief: 'Template story untuk sesi tanya jawab interaktif hari Jumat.',
    objective: 'Customer engagement.',
    dimension: '1080 x 1920 px',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1401',
        taskId: 'task-14',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Draft Created',
        timestamp: hoursAgo(2),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-15',
    taskCode: 'AT-000138',
    title: 'TikTok Affiliate Creator Welcome Card & Guidelines',
    projectId: 'proj-tiktok',
    projectName: 'TikTok Campaign',
    categoryId: 'cat-campaign',
    categoryName: 'Campaign',
    taskType: 'Graphic Design',
    requester: 'Affiliate Marketing Manager',
    assignedUserId: 'user-azhar',
    assignedUserName: 'Azhar',
    assignedUserAvatar: INITIAL_USERS[3].avatar,
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    createdDate: hoursAgo(15),
    startDate: hoursAgo(12),
    deadline: hoursFromNow(16),
    estimatedWorkTime: '3 Jam',
    designBrief: 'Kartu sambutan ucapan terima kasih yang dimasukkan ke dalam paket free sample affiliate.',
    objective: 'Membangun relasi erat dengan top TikTok creator.',
    dimension: '150 x 100 mm (A6 postcard)',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1501',
        taskId: 'task-15',
        userId: 'user-azhar',
        userName: 'Azhar',
        userRole: 'DESIGNER',
        action: 'Work in progress',
        timestamp: hoursAgo(12),
      },
    ],
    attachments: [],
    comments: [],
  },
  {
    id: 'task-16',
    taskCode: 'AT-000139',
    title: 'Shopee Live Special Voucher Backdrop Visual',
    projectId: 'proj-shopee',
    projectName: 'Shopee Campaign',
    categoryId: 'cat-banner',
    categoryName: 'Marketplace Banner',
    taskType: 'Banner',
    requester: 'Live Studio Operations',
    assignedUserId: 'user-havidh',
    assignedUserName: 'Havidh',
    assignedUserAvatar: INITIAL_USERS[1].avatar,
    priority: 'HIGH',
    status: 'ON_HOLD',
    createdDate: hoursAgo(40),
    startDate: hoursAgo(35),
    deadline: hoursFromNow(50),
    estimatedWorkTime: '3 Jam',
    designBrief: 'Banner display backdrop panggung live streaming dengan highlight diskon 40%. Menunggu konfirmasi sponsor.',
    objective: 'Backdrop fisik cetak foam board.',
    dimension: '200 x 150 cm',
    currentVersion: 'V1',
    revisionCount: 0,
    submissions: [],
    revisions: [],
    reassignments: [],
    activityLogs: [
      {
        id: 'log-1601',
        taskId: 'task-16',
        userId: 'user-manager',
        userName: 'Andi Triyanto (Manager)',
        userRole: 'MANAGER',
        action: 'Status Changed to ON_HOLD',
        details: 'Menunggu konfirmasi final logo sponsor partner.',
        timestamp: hoursAgo(30),
      },
    ],
    attachments: [],
    comments: [],
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-manager',
    title: 'Submission Pending Review',
    message: 'Dara telah mengirimkan V2 untuk "Shopee Mega Sale 9.9 Main Header Banner".',
    taskId: 'task-2',
    type: 'SUBMISSION',
    read: false,
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif-2',
    userId: 'user-havidh',
    title: 'Revision Requested',
    message: 'Manager meminta revisi untuk "Poster Shopee Kurma Akram 500g": Perbesar produk sekitar 15%.',
    taskId: 'task-1',
    type: 'REVISION',
    read: false,
    createdAt: hoursAgo(4),
  },
  {
    id: 'notif-3',
    userId: 'user-content',
    title: 'Overdue Task Warning',
    message: 'Task "TikTok Viral Hook Video: Unboxing Kurma Safawi" telah melewati deadline.',
    taskId: 'task-3',
    type: 'OVERDUE',
    read: false,
    createdAt: hoursAgo(1.2),
  },
  {
    id: 'notif-4',
    userId: 'user-manager',
    title: 'Task Overdue Alert',
    message: 'Task "TikTok Viral Hook Video: Unboxing Kurma Safawi" terlambat dikerjakan.',
    taskId: 'task-3',
    type: 'OVERDUE',
    read: true,
    createdAt: hoursAgo(1.2),
  },
  {
    id: 'notif-5',
    userId: 'user-azhar',
    title: 'Task Approved',
    message: 'Selamat! Task "Shopee Flash Sale Hero Banner" telah disetujui oleh Manager.',
    taskId: 'task-6',
    type: 'APPROVAL',
    read: true,
    createdAt: hoursAgo(22),
  },
];
